config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
   get 'welcome/index'

  root 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :lockable, :timeoutable, :omniauthable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  layout :layout_by_resource

  protected

  def layout_by_resource
    if devise_controller?
      "devise"
    elsif user_signed_in?
      "application"
    else
      "welcome"
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <h4>#{sentence}</h4>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end

end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Welcome Chicano Legacy Car Club
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{class: (Rails.env.eql?("production") ? nil : "#{controller.controller_name} #{controller.action_name}")}
    = yield

app/views/layouts/devise.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Welcome Chicano Legacy Car Club
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{class: (Rails.env.eql?("production") ? nil : "#{controller.controller_name} #{controller.action_name}")}
    -if user_signed_in?
      = render "shared/utilites/header/dashboard"
    -else
      = render "shared/utilites/header/welcome"
.container
  .row
    .col-xs-12
      .well.well-lg
        .row
          - if devise_mapping.omniauthable?
            .col-xs-12.col-sm-6
              .visible-xs-block
                = link_to "Back", :back, class: " btn btn-warning pull-right"
              = yield
            .col-xs-12.col-sm-1
              .h3.text-center
                = "or"
            .col-xs-12.col-sm-5
              .hidden-xs
                = link_to "Back", :back, class: " btn btn-warning pull-right"
              = render "devise/shared/social_links"
          - else
            .col-xs-12
              = link_to "Back", :back, class: " btn btn-warning pull-right"
              = yield

app/views/layouts/welcome.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Chicano Legacy Car Club
    = stylesheet_link_tag    'welcome', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'welcome', 'data-turbolinks-track' => true
    = csrf_meta_tags

  %body{class: (Rails.env.eql?("production") ? nil : "#{controller.controller_name} #{controller.action_name}")}
    = render "shared/utilites/header/welcome"
    = yield

app/views/shared/utilites/header/_dashboard.html.haml
%nav#nav.navbar.navbar-default.navbar-static-top.navbar-chicanolegacy
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"aria-controls" => "navbar", "aria-expanded" => "true", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag("logo_header.png", height: "50px")
    #navbar.navbar-collapse.collapse{"aria-expanded" => "true"}
      %ul.nav.navbar-nav
        %li
          %a{:href => "#about"} Test Action
        %li
          %a{:href => "#contact"} Test Action

      %ul.nav.navbar-nav
        - if user_signed_in?

          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Account Settings
              %span.caret
            %ul.dropdown-menu{:role => "menu"}
              %li
                =link_to "edit information", edit_user_registration_path
              %li
                =link_to "edit password", edit_user_password_path
              %li.divider
              %li
                %a{:href => "#"} unlock instructions
          %li
            = link_to "Sign Out", destroy_user_session_path, method: :delete
        -else
          = render "shared/utilites/header/logins"

%header.masthead
  %h1.text-center
    Chicano Legacy Car &amp; Bike Club

app/views/shared/utilites/header/_logins.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    Sign Up
    %strong.caret
  .dropdown-menu.dropdown-menu-right
    = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
      = devise_error_messages!
      .form-group
        = f.label :email, class: "sr-only", "for" => "signUpEmailInput"
        = f.email_field :email, id: "signUpEmailInput", class: "form-control input-sm", placeholder: "email", autofocus: true
      .form-group
        = f.label :password, class: "sr-only", "for" => "signUpEmailPassword"
        - if @validatable
          %em
            (#{@minimum_password_length} characters minimum)
        = f.password_field :password, id: "signUpEmailPassword", class: "form-control input-sm", placeholder: "password", autocomplete: "off"
      .form-group
        = f.label :password_confirmation, class: "sr-only", "for" => "signUpEmailPasswordConfirmation"
        = f.password_field :password_confirmation, id: "signUpEmailPasswordConfirmation", class: "form-control input-sm", placeholder: "confirmation", autocomplete: "off"
      %input#sign-in.btn.btn-primary.btn-block{:type => "submit", :value => "sign up"}
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    Sign In
    %strong.caret
  .dropdown-menu.dropdown-menu-right
    = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
      .form-group
        = f.label :email, class: "sr-only", "for" => "signInEmailInput"
        = f.email_field :email, id: "signInEmailInput", class: "form-control input-sm", placeholder: "email", autofocus: true
      .form-group
        = f.label :password, class: "sr-only", "for" => "signInEmailPassword"
        = f.password_field :password, id: "signInEmailPassword", class: "form-control input-sm", placeholder: "password", autocomplete: "off"
      - if devise_mapping.rememberable?
        .field
          = f.check_box :remember_me
          = f.label :remember_me
      %input#sign-in.btn.btn-primary.btn-block{:type => "submit", :value => "enter"}
    -#%label{:style => "text-align:center;margin-top:5px"} or
    -#%input#sign-in-google.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Google"}
    -#%input#sign-in-twitter.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Twitter"}

app/views/shared/utilites/header/_welcome.html.haml
%nav#nav.navbar.navbar-default.navbar-static-top.navbar-chicanolegacy
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"aria-controls" => "navbar", "aria-expanded" => "true", "data-target" => "#navbar", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag("logo_header.png", height: "50px")
    #navbar.navbar-collapse.collapse{"aria-expanded" => "true"}
      %ul.nav.navbar-nav
        %li
          %a{:href => "#about"} Test Action
        %li
          %a{:href => "#contact"} Test Action
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Test Dropdown
            %span.caret
          %ul.dropdown-menu{:role => "menu"}
            %li
              %a{:href => "#"} Action
            %li
              %a{:href => "#"} Another action
            %li
              %a{:href => "#"} Something else here
            %li.divider
            %li.dropdown-header Nav header
            %li
              %a{:href => "#"} Separated link
            %li
              %a{:href => "#"} One more separated link

      %ul.nav.navbar-nav
        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Sign Up
            %strong.caret
          .dropdown-menu.dropdown-menu-right
            = form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f|
              = devise_error_messages!
              .form-group
                = f.label :email, class: "sr-only", "for" => "signUpEmailInput"
                = f.email_field :email, id: "signUpEmailInput", class: "form-control input-sm", placeholder: "email", autofocus: true
              .form-group
                = f.label :password, class: "sr-only", "for" => "signUpEmailPassword"
                - if @validatable
                  %em
                    (#{@minimum_password_length} characters minimum)
                = f.password_field :password, id: "signUpEmailPassword", class: "form-control input-sm", placeholder: "password", autocomplete: "off"
              .form-group
                = f.label :password_confirmation, class: "sr-only", "for" => "signUpEmailPasswordConfirmation"
                = f.password_field :password_confirmation, id: "signUpEmailPasswordConfirmation", class: "form-control input-sm", placeholder: "confirmation", autocomplete: "off"
              %input#sign-in.btn.btn-primary.btn-block{:type => "submit", :value => "sign up"}


        %li.dropdown
          %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
            Sign In
            %strong.caret
          .dropdown-menu.dropdown-menu-right
            = form_for(resource, as: resource_name, url: session_path(resource_name)) do |f|
              .form-group
                = f.label :email, class: "sr-only", "for" => "signInEmailInput"
                = f.email_field :email, id: "signInEmailInput", class: "form-control input-sm", placeholder: "email", autofocus: true
              .form-group
                = f.label :password, class: "sr-only", "for" => "signInEmailPassword"
                = f.password_field :password, id: "signInEmailPassword", class: "form-control input-sm", placeholder: "password", autocomplete: "off"
              - if devise_mapping.rememberable?
                .field
                  = f.check_box :remember_me
                  = f.label :remember_me
              %input#sign-in.btn.btn-primary.btn-block{:type => "submit", :value => "enter"}
            -#%label{:style => "text-align:center;margin-top:5px"} or
            -#%input#sign-in-google.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Google"}
            -#%input#sign-in-twitter.btn.btn-primary.btn-block{:type => "button", :value => "Sign In with Twitter"}
%header.masthead
  %h1.text-center
    Chicano Legacy Car &amp; Bike Club

app/views/welcome/index.html.haml
#myCarousel.carousel.slide{"data-ride" => "carousel"}
  / Indicators
  %ol.carousel-indicators
    %li.active{"data-slide-to" => "0", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "1", "data-target" => "#myCarousel"}
    %li{"data-slide-to" => "2", "data-target" => "#myCarousel"}
  .carousel-inner{:role => "listbox"}
    .item.active
      %img.intro{alt: "First slide", src: "/assets/2015_06_27.jpg", height: "500px"}
        .container
          .carousel-caption
            %h1 Come out and have a great time!
            %p
              Call 510.812.1903 for more info
    .item
      %img.intro{alt: "Second slide", src: "/assets/eastbay.jpg", height: "500"}
        .container
          .carousel-caption
            %h1 Never forgetting who we are, ORALE!
            %p Proudly representing Chicano Legacy Car Club. ¡Simon que si!
    .item
      %img.intro{alt: "Third slide", src: "/assets/bikes.jpg", height: "500"}
        .container
          .carousel-caption
            %h1 Raza Park
            %p
              Showing off the bikes and having great time!
  %a.left.carousel-control{"data-slide" => "prev", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-left{"aria-hidden" => "true"}
    %span.sr-only Previous
  %a.right.carousel-control{"data-slide" => "next", :href => "#myCarousel", :role => "button"}
    %span.glyphicon.glyphicon-chevron-right{"aria-hidden" => "true"}
    %span.sr-only Net